services:
  # Journal Bot
  facto:
    build:
      context: ./src/facto
      dockerfile: Dockerfile
    image: ${DOCKER_USER:-local}/facto-bot:${IMAGE_TAG:-latest}
    platform: linux/amd64
    restart: always
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy

  # Message Logger Bot
  logta:
    build:
      context: ./src/logta
      dockerfile: Dockerfile
    image: ${DOCKER_USER:-local}/logta-bot:${IMAGE_TAG:-latest}
    platform: linux/amd64
    restart: always
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy

  # MongoDB for message storage
  mongodb:
    image: mongo:7
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all", "--quiet"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # MongoDB replica set initialization (required for change streams)
  mongo-init:
    image: mongo:7
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongosh --host mongodb --eval "
        try {
          rs.status();
        } catch(e) {
          rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongodb:27017'}]});
        }
      "

  # Meilisearch for full-text search
  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: always
    ports:
      - "7701:7700"
    volumes:
      - meili_data:/meili_data
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=${MEILISEARCH_API_KEY:-masterKey}

  # Dashboard Web UI
  dashboard:
    build:
      context: ./src/dashboard
      dockerfile: Dockerfile
      target: runner
    image: ${DOCKER_USER:-local}/facto-dashboard:${IMAGE_TAG:-latest}
    platform: linux/amd64
    restart: always
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/?replicaSet=rs0
      - MONGODB_DATABASE=telegram_logs
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_API_KEY=${MEILISEARCH_API_KEY:-masterKey}
      - NEXT_PUBLIC_WS_PORT=8080
    depends_on:
      mongodb:
        condition: service_healthy
      meilisearch:
        condition: service_started
      mongo-init:
        condition: service_completed_successfully

  # WebSocket server for real-time updates
  dashboard-ws:
    build:
      context: ./src/dashboard
      dockerfile: Dockerfile
      target: websocket
    image: ${DOCKER_USER:-local}/facto-dashboard-ws:${IMAGE_TAG:-latest}
    platform: linux/amd64
    restart: always
    ports:
      - "8081:8081"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/?replicaSet=rs0
      - MONGODB_DATABASE=telegram_logs
      - WS_PORT=8081
    depends_on:
      mongodb:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully

  # Meilisearch sync service
  dashboard-sync:
    build:
      context: ./src/dashboard
      dockerfile: Dockerfile
      target: sync
    image: ${DOCKER_USER:-local}/facto-dashboard-sync:${IMAGE_TAG:-latest}
    platform: linux/amd64
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/?replicaSet=rs0
      - MONGODB_DATABASE=telegram_logs
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_API_KEY=${MEILISEARCH_API_KEY:-masterKey}
    depends_on:
      mongodb:
        condition: service_healthy
      meilisearch:
        condition: service_started
      mongo-init:
        condition: service_completed_successfully

volumes:
  mongo_data:
  meili_data:
